mt6765: Create dummy focaltech firmware files
Following error occurs due to missing firmware files.
This can be solved by just creating dummy firmware files.

../drivers/input/touchscreen/mediatek/ft8006s_spi/focaltech_flash.c:61:10: fatal error: 'include/firmware/fw_helitai_v0e.i' file not found
         ^~~~~~~~~~~~~~~~~~~
../drivers/input/touchscreen/mediatek/ft8006s_spi/focaltech_config.h:246:50: note: expanded from macro 'FTS_UPGRADE_FW_FILE'
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Change-Id: I5b3244109ea0619e9b22ce6c9472032199850181
Signed-off-by: techdiwas <diwasneupane652@gmail.com>